config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"

  #Twitter user
  get '/login_with_twitter', to: redirect('/auth/twitter')
  get '/auth/twitter/callback', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  #Site user
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create, :new]

  #Twilio
  post 'twilio/sms' => 'twilio#sms'

  #Twitter
  post 'twitter/follow_back' => 'twitter#follow_back'
  post "twitter/search" => 'twitter#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	#Validations
	validates :name, presence: true
	validates :email, presence: true,
					  uniqueness: {message: 'Email has already been registered, try a different one'},
					  if: :email_required?
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, 
								if: :email_required?
	has_secure_password validations: false, if: :password_required?
	validates :password, presence: {message: 'Password cannot be blank'},
						 length: {within: 8..20, message: 'Password length must be between 8 to 20'},
						 if: :password_required?

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.name = auth.info.name
			user.location = auth.info.location
			user.image = auth.info.image
			user.twitter = auth.info.urls.Twitter
			user.token = auth.credentials.token
			user.secret = auth.credentials.secret
			user.save!
			return user
		end
	end

	def email_required?
		provider.blank? 
	end

	def password_required?
		provider.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		if current_user
			# current_user.update_token
		else
			auth = request.env["omniauth.auth"]
			if auth
				user = User.from_omniauth(auth)
				session[:user_id] = user.id
				flash[:success] = "Welcome, #{user.name}"
			else
				user =  User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
				if user
					session[:user_id] = user.id
					flash[:success] = "Welcome, #{user.name}"
				else
					flash[:error] = "Failed to login"
				end
			end
		end
		redirect_to root_path
	end

	def destroy
		session.clear
		flash[:success] = "See you again!"
		redirect_to root_path
	end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
	skip_before_action :verify_authenticity_token

	def sms
	    message_body = params["Body"]
	    from_number = params["From"]

	    twitter_client.update(message_body)

	    twilio_client.messages.create(
	      from: ENV["TWILIO_PHONE_NUMBER"],
	      to: from_number,
	      body: "Hello there, thanks for tweeting with Ochi Tweetor! Your number is #{from_number}. Your tweet has been posted!"
	    )
	end

	private

		def twilio_client
			@twilio_client = Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"])
		end

		def twitter_client
			@twitter_client ||= Twitter::REST::Client.new do |config|
				config.consumer_key        = ENV["TWITTER_API_KEY"]
				config.consumer_secret     = ENV["TWITTER_API_SECRET"]
				config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
				config.access_token_secret = ENV["TWITTER_ACCESS_TOKEN_SECRET"]
			end
		end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

	def follow_back
		if current_user
			if !current_user.provider.nil?
				@follow_back = []
				@twitter_client = twitter_client
				friends = @twitter_client.friends
				followers = @twitter_client.followers
				following_requested = @twitter_client.friendships_outgoing
				followers.each do |follower|
					if !friends.include?(follower)
						if !following_requested.include?(follower.id)
							@twitter_client.follow(follower.id)
							@follow_back << follower
						end
					end
				end
				flash[:success] = "Followed back all your followers"
			else
				flash[:error] = "Sorry, the follow back feature is not available to non-twitter account"
			end
		else
			flash[:error] = "Please login with your twitter account to enable the follow back feature "
		end
		redirect_to root_path
	end

	def search
		if params[:search]
			@twitter_client = twitter_client
			@tweets = @twitter_client.search(params[:search], result_type: "popular").take(10)
			@tweets_oembeds = @twitter_client.oembeds(@tweets)
			respond_to do |format|
				format.html { redirect_to root_path,  flash: {success: "Successfully found 10 of the most popular tweets about #{params[:search]}"} }
				format.js
			end
		else
			respond_to do |format|
				format.html { redirect_to root_path,  flash: {error: "Failed to search, please try again by putting keyword"} }
				format.js
			end
		end
	end

	private

		def twitter_client
			@twitter_client ||= Twitter::REST::Client.new do |config|
				config.consumer_key        = ENV["TWITTER_API_KEY"]
				config.consumer_secret     = ENV["TWITTER_API_SECRET"]
				config.access_token        = current_user.token
				config.access_token_secret = current_user.secret
			end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, flash: { success: "Successfully created user!" } }
      else
        format.html { redirect_to root_path, flash: { error: "Failed to create user!" } }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		session.has_key? :user_id
	end

	def flash_class(level)
	    case level
	        when "success" then "alert alert-success"
	        when "error" then "alert alert-danger"
	        when "info" then "alert alert-info"
	        when "warning" then "alert alert-warning"
	    end
	end
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">OchiTweetor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if !current_user %>
          <li class="nav-item">
            <%= link_to image_tag('sign_in_with_twitter.png'), login_with_twitter_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login with email", new_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OchiTweetor</title>
    <%= csrf_meta_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash_#{key} #{flash_class(key)}" %>
  <%= javascript_tag "$('.flash_#{key}').fadeOut(5000);" %>
<% end %>
<% if current_user %>
	<% if !current_user.provider.nil? %>
		<%= link_to "Follow back all your followers!", twitter_follow_back_path, method: :post %>
		<div class='content'>
		  <div id="search-box">
		    <%= form_tag 'twitter/search', method: :post, remote: true do %>
		      <%= text_field_tag 'search', nil, placeholder: "Type in any keyword to search on Twitter", style: "width: 500px;"%>
		      <button type="submit">Search</button>
		    <% end %>
		  </div>
		</div>
	<% else %>
		<p>Looks like you decided to sign in with email, so no twitter functions for you</p>
	<% end %>
<% else %>
	<p>Sign in with twitter to use the twitter functions</p>
<% end %>

<div class="tweets-found">
</div>

<div class="twitter-embed">
	<h1>Live tweets about 2017 LOL World Championship </h1>
	<a class="twitter-timeline" href="https://twitter.com/hashtag/Worlds2017" data-widget-id="920989036558168066">#Worlds2017 Tweets</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/twitter/_tweets_found.html.erb
<% if @tweets_oembeds %>
	<h1>10 Most Popular Search Results Found</h1>
	<% @tweets_oembeds.each do |oembed| %>
		<%= raw(oembed.html) %>
	<% end %>
<% end %>

app/views/twitter/search.js.erb
$('.tweets-found').empty().append('<%= j render("tweets_found") %>');

app/views/users/_form.html.erb
<%= form_for @user, class: "form-horizontal" do |form| %>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2>Register New User</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <%= form.label :name %>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                    <%= form.text_field :name, type: 'string', class: "form-control", placeholder: "Name", autofocus: true %>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <%= form.label :email %>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-at"></i></div>
                    <%= form.text_field :email, type: 'email', class: "form-control", placeholder: "you@example.com", autofocus:true %>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <%= form.label :password %>
        </div>
        <div class="col-md-6">
            <div class="form-group has-danger">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                    <%= form.password_field :password, class: "form-control", placeholder: "Password", required: true %>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <%= button_tag type: 'submit', class: "btn btn-success" do %>
              <i class="fa fa-user-plus"></i>
              Register
            <% end %>
            <%= link_to new_session_path, class: "btn btn-primary" do%>
               <i class="fa fa-sign-in"></i>
               Sign in
            <% end %>
        </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>